# Nombre del microservicio
spring.application.name=catalogo-service

# Puerto dinámico para Render (usa el que asigne la plataforma, si no encuentra ninguno usa el 8080 por defecto)
server.port=${PORT:8080}

# Conexión a NeonTech (PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-dawn-poetry-apqfw71e-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_HicOqfERJz76
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true